# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    branches:
      only:
        - dev
    working_directory: ~/repo # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.15.3 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      #- run: npm install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Script for cleaning the previous deploy /home/ubuntu/studystates-server/dev
      - run: ssh -o StrictHostKeyChecking=no ubuntu@13.125.87.26 "/home/ubuntu/studystates-server/deploy-clean.sh"

      # upload all the code to machine
      - run:
          name: AWS EC2 deploy
          command: |
            # Create archive.
            tar -zcvf dev.tar.gz ./

            # Script for cleaning the previous deploy /home/ubuntu/studystates-server/dev
            scp -r -o StrictHostKeyChecking=no ./dev.tar.gz ubuntu@13.125.87.26:/home/ubuntu/studystates-server/dev

      # Script for building in this release.
      - run: ssh -o StrictHostKeyChecking=no ubuntu@13.125.87.26 "/home/ubuntu/studystates-server/dev/deploy-build.sh"
